dataset_id: "nlphuji/flickr30k"
dataset_name: "TEST"
image_column: "image"
text_column: "caption"
caption_is_list: true
split_train: "train"
split_test: "test"

model_name: "google/siglip-base-patch16-224"
batch_size: 64
num_workers: 4
device: "cuda"
out_dir: "/workspace/experiments/flickr30k_siglip_eliplite"

# ELIP-lite
n_prompts: 10
lr: 1e-3
epochs: 3
temperature: 0.07
save_every: 1